import type { MediaPurpose, MediaStatus, MediaType } from "@/config/media";

/**
 * Media (photo) metadata. Mirrors the `media` table
 * (supabase/migrations/20260829156000_media.sql, extended by
 * 20260909120000_media_storage.sql).
 *
 * Mission 030 added `purpose`, `status` and `updatedAt`, and made
 * `sizeBytes` nullable — see the migration for why each of those is
 * shaped the way it is.
 */
export interface Media {
  id: string;
  memorialId: string;
  ownerId: string;
  /**
   * Internal HERITAGE path — `<memorialId>/<mediaId>/original.<ext>`,
   * generated by lib/media/media-path.ts. Never a provider URL: the
   * bucket is private, so a usable URL is a short-lived signed one
   * minted per read and never stored (see supabase/README.md).
   */
  storagePath: string;
  mediaType: MediaType;
  /**
   * What this media is for. The ONLY difference between a Hero media
   * and a Gallery media — they share one table, one bucket, one path
   * shape, one ownership check and one engine.
   */
  purpose: MediaPurpose;
  /**
   * Whether the bytes have been verified. Nothing displays a `pending`
   * media: its object may be absent, truncated, or not an image at all.
   */
  status: MediaStatus;
  /**
   * While `pending`, the type the client DECLARED (used only to derive
   * the path extension). Once `ready`, the type verified from the
   * object's own byte signature.
   */
  mimeType: string;
  /**
   * Kept from Mission 002 and never written by the Mission 030
   * foundation — a client filename is attacker-controlled and often
   * carries personal data. See the column comment in the migration.
   */
  originalFilename: string | null;
  /**
   * MEASURED from the stored object at finalization, never declared by
   * the client. `null` while `pending`, because the file does not exist
   * yet; always present once `ready`.
   */
  sizeBytes: number | null;
  width: number | null;
  height: number | null;
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601
}
