/**
 * Mission 042 — the canonical Traditions & repères (A09) content model.
 *
 * This is the content behind the `announcement` editorial context's own
 * A09 step (lib/builder/guided-flow/human-steps.ts): a facultative,
 * passable list of practices/consignes the family explicitly confirms —
 * never inferred, never precomputed, never dependent on Ceremony data
 * (mission brief sections 2-3, 11).
 *
 * This file only defines the SHAPE, exactly like types/ceremony.ts does
 * for the Ceremony. Parsing, normalization, validation and the draft-
 * integration helpers (inspect/read/write) live in
 * lib/memorial/traditions.ts. No UI, no A09 screen, no wording, and no
 * cultural content of any kind are built or referenced here — the
 * catalog of editorial suggestions (config/tradition-suggestions.ts) is
 * a separate, deliberately empty-by-default configuration this model
 * never imports (mission brief section 6: no cultural text hardcoded
 * anywhere in TypeScript).
 *
 * ## One entry, two possible origins, never a default selection
 *
 * `origin: "custom"` — the family wrote this repère in their own words,
 * from nothing. `origin: "suggestion"` — the family explicitly picked an
 * editorial suggestion (and may have edited its text) from whatever
 * catalog their offer/skin currently allows. Either way, an entry only
 * ever exists here once the family has taken an explicit confirming
 * action (mission brief section 9) — displaying a suggestion never, by
 * itself, creates one of these.
 *
 * `suggestionId` is the provenance link back to
 * `config/tradition-suggestions.ts`'s catalog, kept ONLY for a
 * `"suggestion"`-origin entry (`null` for `"custom"`) — never a second
 * source of truth for what the entry actually says. What the mémorial
 * renders is always this entry's own `text`, confirmed and possibly
 * edited by the family, never a live re-read of the suggestion catalog —
 * so a catalog that changes or removes a suggestion tomorrow can never
 * alter what a family already confirmed (mission brief section 8's own
 * "ce qui appartient réellement au mémorial doit rester lisible depuis
 * les données du mémorial même si une bibliothèque éditoriale évolue
 * plus tard").
 *
 * ## No religion, no belief, no inferred practice
 *
 * Deliberately absent from this type, and from every module that reads
 * or writes it: any field naming a religion, a confession, a community,
 * or a courant (mission brief section 4). `text` is the family's own
 * words, verbatim — this model records that a repère was confirmed, not
 * what it "means" or which tradition it supposedly belongs to.
 *
 * ## No Ceremony duplication
 *
 * Deliberately absent: date, heure, lieu, adresse, accès, stationnement,
 * or any other field already structurally owned by Ceremony
 * (types/ceremony.ts). If a family's own free `text` happens to mention
 * a date or a place, that text is preserved verbatim like any other
 * family content (mission brief section 11) — HERITAGE simply never
 * creates that duplication itself.
 *
 * ## The index signature is a TypeScript-only necessity — NOT a runtime
 * permission
 *
 * Identical device, identical reason, as `CeremonyContent`'s own
 * docstring: `[key: string]: unknown` exists solely so this type is
 * structurally assignable into `MemorialSectionContent`
 * (`Record<string, unknown>`, types/memorial.ts). The actual, strict
 * boundary is `lib/memorial/traditions.ts`'s `parseTraditionsContent`:
 * any key beyond the ones named below makes the whole value
 * `"corrupted"`.
 */
export interface TraditionEntry {
  [key: string]: unknown;
  /** A stable identifier for THIS instance, unique within one
   * `TraditionsContent.entries` list — never reused after removal, and
   * never derived from `title`/`text` (so an edit never changes an
   * entry's identity). Generated by the caller (a Client Component) at
   * the moment the family confirms the entry; this model never
   * generates one itself (this module has no I/O, no clock, no random
   * source of its own — same discipline as every other pure content
   * model in this codebase). */
  id: string;
  /** `"custom"` — written by the family from nothing. `"suggestion"` —
   * started from an editorial suggestion the family explicitly picked
   * (mission brief section 9: never picked FOR them). */
  origin: "custom" | "suggestion";
  /** The suggestion this entry started from, iff `origin === "suggestion"`
   * — always `null` for `origin === "custom"` (a custom repère is never
   * retroactively linked to a suggestion it didn't come from). Purely
   * provenance/analytics; never re-read to derive this entry's actual
   * text (see this file's own docstring). */
  suggestionId: string | null;
  /** A short, facultative title the family may give this repère —
   * `null` means none given, never invalid. */
  title: string | null;
  /** The family's own confirmed text — the ONE thing this model exists
   * to preserve verbatim, never translated, never reformulated, never
   * analyzed (mission brief section 10). Always non-blank for a
   * persisted entry: a repère with nothing to say is not a repère —
   * `lib/memorial/traditions.ts`'s `addTraditionEntry` enforces this at
   * the moment of confirmation. */
  text: string;
}

export interface TraditionsContent {
  [key: string]: unknown;
  /** Every repère the family has explicitly confirmed, in the order
   * they added them. Empty is the normal, fully-valid state — A09 is
   * entirely facultative and passable (mission brief section 13): an
   * empty list is not an error, and this model has no separate
   * "touched"/"visited" flag of its own — that belongs to
   * `content.guidedFlow.A09` (lib/builder/guided-flow/traditions-step.ts),
   * exactly like every other Guided Flow step. */
  entries: TraditionEntry[];
}

/** `TraditionsContent` with no repère at all — A09 fully skipped, or not
 * yet visited. */
export const EMPTY_TRADITIONS_CONTENT: TraditionsContent = {
  entries: [],
};
