/**
 * Mission 015B — the audited Admin mutations over `entitlements`.
 *
 * A separate, minimal port rather than new methods on
 * `EntitlementRepository`: everything here writes, everything here is
 * audited, and everything here is reachable ONLY from HERITAGE staff —
 * three properties `EntitlementRepository` does not share and must not
 * be made to share. Keeping them apart means no owner-facing code path
 * can reach an Admin mutation by accident, and no future method added
 * here ever needs to worry about what redemption expects of it.
 *
 * Both methods below are one PostgreSQL RPC call each
 * (admin_mutate_activation_key, admin_revoke_entitlement —
 * supabase/migrations/20260904100000_admin_audit_and_mutations.sql).
 * That is the whole contract: the mutation and its audit row commit
 * together, in one transaction, inside the function. This port has no
 * equivalent of `EntitlementRepository.swapActivationKey()` — a second,
 * unaudited way to change `activation_key_hash` from application code
 * would defeat the audit this mission exists to add. See
 * lib/admin/admin-entitlement-repository-boundary.test.ts.
 */

export type AdminActivationKeyMutationOutcome =
  | { status: "replaced" }
  | { status: "invalidated" }
  /** No entitlement with this id. */
  | { status: "notFound" }
  /** The entitlement exists but is not `available` (redeemed or
   * revoked). Nothing was read out as a reason beyond that — support
   * does not need finer detail to know a mutation did not happen. */
  | { status: "notAvailable" };

export type AdminRevokeEntitlementOutcome =
  | { status: "revoked" }
  | { status: "notFound" }
  /** Refused because the entitlement is not `available` — already
   * `redeemed` (a family's right; not support's to take back) or already
   * `revoked` (never a second audit row for the same fact).
   * `blockingStatus` names which, for a clearer refusal message. */
  | { status: "notAvailable"; blockingStatus: "redeemed" | "revoked" };

export interface AdminEntitlementRepository {
  /**
   * Replaces or invalidates the activation key of an `available`
   * entitlement.
   *
   * `nextActivationKeyHash: null` invalidates; a 64-hex sha256 replaces.
   * The raw key is never a parameter here — only its hash, generated by
   * lib/entitlement/activation-key.ts before this is ever called.
   *
   * `adminAuthUserId` must come from a validated staff session
   * (Mission 014's `requireHeritageAdmin`), resolved server-side. It is
   * never supplied by, or derived from, anything a browser sent.
   */
  mutateActivationKey(input: {
    entitlementId: string;
    nextActivationKeyHash: string | null;
    adminAuthUserId: string;
  }): Promise<AdminActivationKeyMutationOutcome>;

  /**
   * Revokes an `available` entitlement: `status` becomes `revoked` and
   * `activation_key_hash` becomes NULL, together, in the same
   * transaction as the audit row. A right already `redeemed` or already
   * `revoked` is refused, never overwritten.
   */
  revokeEntitlement(input: {
    entitlementId: string;
    adminAuthUserId: string;
  }): Promise<AdminRevokeEntitlementOutcome>;
}
