import { CANONICAL_IMAGE_EXTENSION, type AllowedImageMimeType } from "@/config/media";

/**
 * Mission 030 — object paths, generated by HERITAGE and by nothing else.
 *
 * ## The shape
 *
 *     <memorialId>/<mediaId>/original.<ext>
 *
 * e.g. `9f1c.../3a7e.../original.jpg`
 *
 * Three properties, each of which is the reason for one segment:
 *
 *   * `<memorialId>` first — an object's owning memorial is readable
 *     from its path alone, so a stray object can always be attributed,
 *     and a prefix listing per memorial is natural if it is ever
 *     needed.
 *   * `<mediaId>` second — every upload gets its OWN directory, so no
 *     upload can ever write over another's object. This is what makes
 *     replacement safe without any locking: a new Hero photo is a new
 *     media id, so it lands somewhere the old one is not, and the old
 *     one keeps working until the new one is proven good.
 *   * `original.<ext>` last — names the role of the file within its
 *     media. Future derivatives (Mission 047's optimized/responsive
 *     variants, Mission 033's Hero crop) become siblings —
 *     `hero-1200.webp`, `thumb.webp` — under the same media id, with no
 *     migration and no second bucket. Mission 030 creates none of them;
 *     it just does not stand in their way (section 18).
 *
 * ## What is deliberately absent from a path
 *
 * No email, no person's name, no activation key, no Etsy order id, no
 * client filename, no slug. Both ids are opaque server-generated
 * UUIDs — a path leaks nothing about the family even if it is
 * shoulder-surfed out of a signed URL, and it cannot be guessed
 * (mission brief, section 7).
 *
 * The client's filename in particular is never any part of this. It is
 * attacker-controlled and would be the obvious traversal vector; here
 * it simply has no route into the path at all, which is stronger than
 * sanitizing it. The extension comes from the VERIFIED type, not from
 * the name the browser sent.
 */

/**
 * The canonical UUID form both ids must have.
 *
 * Anchored at both ends and case-insensitive. This is what makes
 * traversal structurally impossible rather than filtered: `..`, `/`,
 * `\`, a URL-encoded `%2e%2e`, a NUL byte, a leading `-`, an absolute
 * path and a 300-character name all fail to be a UUID, so none of them
 * can reach the path builder. There is no blocklist to keep up to date
 * because nothing is being subtracted — only an exact shape is
 * admitted.
 */
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isMediaIdentifier(value: unknown): value is string {
  return typeof value === "string" && UUID_PATTERN.test(value);
}

/**
 * Thrown when a caller tries to build a path from something that is not
 * a pair of UUIDs.
 *
 * This one DOES throw, unlike every other refusal in this foundation,
 * and the asymmetry is deliberate. A bad memorial id or a bad media id
 * reaching here is not a user error to report — the primitives verify
 * ownership and generate the media id themselves, so by construction
 * both values are already known-good by the time a path is built.
 * Reaching this line means a caller found a way around that, which is a
 * programming fault. Returning a result would let it be ignored; the
 * one thing that must not happen is a path getting built anyway.
 */
export class InvalidMediaPathError extends Error {
  constructor() {
    // No interpolation of the offending value: this message can reach a
    // log, and the whole point is that the input was untrusted.
    super("Refusing to build a media object path from a non-identifier value.");
    this.name = "InvalidMediaPathError";
  }
}

/**
 * The object path for one media's original file.
 *
 * Takes the VERIFIED mime type rather than a filename or an extension,
 * so the only thing that can determine the extension is what the bytes
 * turned out to be.
 */
export function buildMediaObjectPath(input: {
  memorialId: string;
  mediaId: string;
  mimeType: AllowedImageMimeType;
}): string {
  if (!isMediaIdentifier(input.memorialId) || !isMediaIdentifier(input.mediaId)) {
    throw new InvalidMediaPathError();
  }

  const extension = CANONICAL_IMAGE_EXTENSION[input.mimeType];

  // A mime type outside the allowlist yields `undefined` here rather
  // than a path ending in "original.undefined". Belt and braces: the
  // type system already forbids it, but this function's output is a
  // security boundary and a `Record` lookup is not a runtime guarantee.
  if (!extension) {
    throw new InvalidMediaPathError();
  }

  return `${input.memorialId}/${input.mediaId}/original.${extension}`;
}

/**
 * The prefix under which every object belonging to one media lives.
 *
 * Used by deletion, which must remove the whole media directory — the
 * original today, and whatever derivatives Missions 033/047 add
 * alongside it later. Deleting by prefix rather than by the single
 * known path means those future files cannot become orphans the day
 * they are introduced.
 */
export function buildMediaObjectPrefix(input: {
  memorialId: string;
  mediaId: string;
}): string {
  if (!isMediaIdentifier(input.memorialId) || !isMediaIdentifier(input.mediaId)) {
    throw new InvalidMediaPathError();
  }

  return `${input.memorialId}/${input.mediaId}`;
}

/**
 * Whether `path` genuinely belongs to `memorialId`.
 *
 * The guard for every operation that acts on a path READ BACK from the
 * database. Ownership was verified against a memorial id; this proves
 * the path about to be deleted or signed is under that same memorial,
 * so a corrupted or tampered row can never redirect an authorized
 * operation at another family's object.
 *
 * Compares against `<memorialId>/` — the trailing separator matters. A
 * bare `startsWith(memorialId)` would also match a different memorial
 * whose id merely began with the same characters, which UUIDs make
 * unlikely but not impossible to arrange.
 */
export function isPathWithinMemorial(path: string, memorialId: string): boolean {
  if (!isMediaIdentifier(memorialId)) return false;
  if (typeof path !== "string" || path.length === 0) return false;

  // Re-checked here rather than assumed: this function's input is a
  // stored value, and a stored value is only as trustworthy as whatever
  // wrote it. A path containing a traversal segment is refused outright
  // even if its prefix looks right.
  if (path.includes("..") || path.includes("\\") || path.startsWith("/")) return false;

  return path.startsWith(`${memorialId}/`);
}
