import { describe, expect, it } from "vitest";
import {
  InvalidMediaPathError,
  buildMediaObjectPath,
  buildMediaObjectPrefix,
  isMediaIdentifier,
  isPathWithinMemorial,
} from "./media-path";
import { MEMORIAL_A, MEMORIAL_B } from "./test-fixtures";

const MEDIA_ID = "cccccccc-cccc-4ccc-8ccc-cccccccccccc";

/**
 * Mission 030, section 7 — the path is generated by HERITAGE, contains
 * no personal data, and cannot be influenced by the browser.
 */
describe("buildMediaObjectPath", () => {
  it("produces <memorialId>/<mediaId>/original.<ext>", () => {
    expect(
      buildMediaObjectPath({ memorialId: MEMORIAL_A, mediaId: MEDIA_ID, mimeType: "image/jpeg" }),
    ).toBe(`${MEMORIAL_A}/${MEDIA_ID}/original.jpg`);
  });

  it("derives the extension from the type, never from a filename", () => {
    expect(
      buildMediaObjectPath({ memorialId: MEMORIAL_A, mediaId: MEDIA_ID, mimeType: "image/png" }),
    ).toMatch(/original\.png$/);
    expect(
      buildMediaObjectPath({ memorialId: MEMORIAL_A, mediaId: MEDIA_ID, mimeType: "image/webp" }),
    ).toMatch(/original\.webp$/);
  });

  it("gives every media its own directory", () => {
    // The property that makes replacement safe with no locking: a new
    // upload cannot land on an existing object's path.
    const first = buildMediaObjectPath({
      memorialId: MEMORIAL_A,
      mediaId: MEDIA_ID,
      mimeType: "image/jpeg",
    });
    const second = buildMediaObjectPath({
      memorialId: MEMORIAL_A,
      mediaId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
      mimeType: "image/jpeg",
    });

    expect(first).not.toBe(second);
  });

  it("puts the memorial first, so any object can be attributed", () => {
    const path = buildMediaObjectPath({
      memorialId: MEMORIAL_A,
      mediaId: MEDIA_ID,
      mimeType: "image/jpeg",
    });

    expect(path.startsWith(`${MEMORIAL_A}/`)).toBe(true);
  });

  it("leaks nothing personal — only two UUIDs and a fixed filename", () => {
    const path = buildMediaObjectPath({
      memorialId: MEMORIAL_A,
      mediaId: MEDIA_ID,
      mimeType: "image/jpeg",
    });

    // No email, no name, no key, no order id — the path is entirely
    // composed of server-generated opaque identifiers.
    expect(path).toBe(`${MEMORIAL_A}/${MEDIA_ID}/original.jpg`);
    expect(path).not.toMatch(/@/);
  });
});

describe("buildMediaObjectPath — hostile input", () => {
  /**
   * Every one of these is a value an attacker would supply if a client
   * filename or a raw id ever reached the path builder. None of them is
   * a UUID, so none of them can produce a path at all — the defence is
   * an exact shape, not a blocklist that must be kept current.
   */
  const HOSTILE = [
    "../../../etc/passwd",
    "..",
    "../",
    "a/../../b",
    "/absolute/path",
    "..\\..\\windows",
    "%2e%2e%2f",
    "photo.jpg",
    "évil.jpg",
    "a".repeat(500),
    "",
    "   ",
    `${MEMORIAL_A}/../${MEMORIAL_B}`,
    "cccccccc-cccc-4ccc-8ccc-cccccccccccc/../../x",
  ];

  it("refuses a hostile memorial id", () => {
    for (const hostile of HOSTILE) {
      expect(() =>
        buildMediaObjectPath({ memorialId: hostile, mediaId: MEDIA_ID, mimeType: "image/jpeg" }),
      ).toThrow(InvalidMediaPathError);
    }
  });

  it("refuses a hostile media id", () => {
    for (const hostile of HOSTILE) {
      expect(() =>
        buildMediaObjectPath({ memorialId: MEMORIAL_A, mediaId: hostile, mimeType: "image/jpeg" }),
      ).toThrow(InvalidMediaPathError);
    }
  });

  it("refuses a mime type outside the allowlist even if the types were bypassed", () => {
    expect(() =>
      buildMediaObjectPath({
        memorialId: MEMORIAL_A,
        mediaId: MEDIA_ID,
        // Cast on purpose: this is what a bug or an `any` upstream
        // would look like at runtime, and the path builder is a
        // security boundary that must not rely on the type system.
        mimeType: "image/svg+xml" as never,
      }),
    ).toThrow(InvalidMediaPathError);
  });

  it("never mentions the offending value in its error", () => {
    // The message can reach a log; the input was untrusted.
    try {
      buildMediaObjectPath({
        memorialId: "../../secret",
        mediaId: MEDIA_ID,
        mimeType: "image/jpeg",
      });
      throw new Error("expected a refusal");
    } catch (error) {
      expect((error as Error).message).not.toContain("secret");
    }
  });
});

describe("buildMediaObjectPrefix", () => {
  it("names the whole media directory", () => {
    expect(buildMediaObjectPrefix({ memorialId: MEMORIAL_A, mediaId: MEDIA_ID })).toBe(
      `${MEMORIAL_A}/${MEDIA_ID}`,
    );
  });

  it("refuses hostile ids exactly as the path builder does", () => {
    expect(() =>
      buildMediaObjectPrefix({ memorialId: "../..", mediaId: MEDIA_ID }),
    ).toThrow(InvalidMediaPathError);
    expect(() =>
      buildMediaObjectPrefix({ memorialId: MEMORIAL_A, mediaId: "../.." }),
    ).toThrow(InvalidMediaPathError);
  });
});

describe("isMediaIdentifier", () => {
  it("accepts a UUID in either case", () => {
    expect(isMediaIdentifier(MEMORIAL_A)).toBe(true);
    expect(isMediaIdentifier(MEMORIAL_A.toUpperCase())).toBe(true);
  });

  it("rejects anything that is not exactly a UUID", () => {
    for (const value of [
      null,
      undefined,
      42,
      {},
      [],
      "",
      "not-a-uuid",
      `${MEMORIAL_A} `,
      ` ${MEMORIAL_A}`,
      `${MEMORIAL_A}/x`,
      `x${MEMORIAL_A}`,
      MEMORIAL_A.replace(/-/g, ""),
      `${MEMORIAL_A}\n${MEMORIAL_B}`,
    ]) {
      expect(isMediaIdentifier(value)).toBe(false);
    }
  });

  it("is anchored, so a UUID embedded in a longer string is refused", () => {
    // An unanchored pattern would accept `../../<uuid>`, which is
    // precisely the traversal this shape exists to make impossible.
    expect(isMediaIdentifier(`../../${MEMORIAL_A}`)).toBe(false);
  });
});

describe("isPathWithinMemorial", () => {
  it("accepts a path genuinely under the memorial", () => {
    expect(isPathWithinMemorial(`${MEMORIAL_A}/${MEDIA_ID}/original.jpg`, MEMORIAL_A)).toBe(true);
  });

  it("refuses another memorial's path", () => {
    // The guard that stops a tampered stored row from aiming a
    // verified-and-authorized delete at another family's object.
    expect(isPathWithinMemorial(`${MEMORIAL_B}/${MEDIA_ID}/original.jpg`, MEMORIAL_A)).toBe(false);
  });

  it("requires the separator, so a prefix collision is not a match", () => {
    expect(isPathWithinMemorial(`${MEMORIAL_A}extra/x.jpg`, MEMORIAL_A)).toBe(false);
    expect(isPathWithinMemorial(MEMORIAL_A, MEMORIAL_A)).toBe(false);
  });

  it("refuses a stored path containing traversal, even under the right prefix", () => {
    expect(isPathWithinMemorial(`${MEMORIAL_A}/../${MEMORIAL_B}/x.jpg`, MEMORIAL_A)).toBe(false);
    expect(isPathWithinMemorial(`${MEMORIAL_A}/..\\x.jpg`, MEMORIAL_A)).toBe(false);
  });

  it("refuses an absolute path", () => {
    expect(isPathWithinMemorial(`/${MEMORIAL_A}/x.jpg`, MEMORIAL_A)).toBe(false);
  });

  it("refuses everything when the memorial id is not an identifier", () => {
    expect(isPathWithinMemorial(`${MEMORIAL_A}/x.jpg`, "../..")).toBe(false);
    expect(isPathWithinMemorial("", MEMORIAL_A)).toBe(false);
  });
});
