import { MAX_MEDIA_BYTES, MEDIA_PURPOSES, type MediaPurpose } from "@/config/media";
import { authorizeMemorialAccess } from "@/lib/auth/memorial-access";
import type { HeritageActor } from "@/lib/auth/heritage-actor";
import type { Media } from "@/types/media";
import {
  mediaFailure,
  mediaSuccess,
  type MediaResult,
} from "./media-errors";
import {
  buildMediaObjectPath,
  buildMediaObjectPrefix,
  isPathWithinMemorial,
} from "./media-path";
import {
  IMAGE_SIGNATURE_BYTES,
  detectImageMimeType,
  isAllowedImageMimeType,
} from "./image-signature";
import type { MediaEngineDeps } from "./media-engine";

/**
 * Mission 030 — creating a media, in two server-verified steps.
 *
 * ## The model, and why the bytes do not pass through us
 *
 *   1. an authenticated Owner asks to upload to a memorial;
 *   2. the server proves the Owner really owns that memorial;
 *   3. HERITAGE generates the media id and the object path;
 *   4. the server issues a permission to write THAT ONE OBJECT;
 *   5. the browser uploads straight to Storage;
 *   6. the server verifies the stored bytes and finalizes;
 *   7. the media becomes usable.
 *
 * Steps 2-4 are `reserveMediaUpload`; step 6-7 is
 * `finalizeMediaUpload`.
 *
 * The bytes go browser -> Storage directly, never through a Server
 * Action or a Netlify Function. That is a deliberate architectural
 * choice, not a performance tweak (mission brief, section 9):
 * Netlify's synchronous function payload ceiling is around 6 MB, below
 * a normal smartphone photograph, so routing uploads through our own
 * runtime would have made the hosting platform's limit into HERITAGE's
 * product limit. It also keeps a 15 MiB transfer off the request path
 * entirely.
 *
 * What we give up by not seeing the bytes in flight is the ability to
 * validate them before they are stored — which is exactly why step 6
 * exists and why nothing is usable until it has run.
 *
 * ## What the upload permission is
 *
 * A short-lived token authorizing a write to ONE path. It is not a
 * session, not a bucket key, and it cannot be redirected: the path was
 * generated by us in step 3 from ids we control. A stolen permission
 * buys an attacker the ability to write one object they cannot read,
 * under a media id that is already reserved, for two minutes. It is
 * never "access to the bucket" (mission brief, section 10).
 */

/** What the browser needs to perform the upload, and nothing more. */
export interface ReservedUpload {
  /** Server-generated. The caller never chooses this. */
  mediaId: string;
  /** Server-generated. Echoed so a client can be debugged, never trusted back. */
  storagePath: string;
  uploadUrl: string;
  uploadToken: string;
}

export async function reserveMediaUpload(
  deps: MediaEngineDeps,
  actor: HeritageActor,
  input: { memorialId: string; purpose: MediaPurpose; declaredMimeType: string },
): Promise<MediaResult<ReservedUpload>> {
  // Ownership FIRST, before any validation, any id generation and any
  // database write. A visitor, or an Owner pointing at somebody else's
  // memorial, must not be able to cause so much as a row to be created
  // — and must not be able to learn anything from how quickly they were
  // refused.
  //
  // `memorialId` arriving from the browser is expected and fine: it is
  // a claim. This is the line that turns it into a verified fact
  // (lib/auth/memorial-access.ts).
  const access = await authorizeMemorialAccess(deps, actor, input.memorialId);
  if (access.status !== "granted") {
    return mediaFailure("access_denied");
  }

  if (!(MEDIA_PURPOSES as readonly string[]).includes(input.purpose)) {
    // Not `unsupported_format`: nothing is wrong with the file, the
    // request itself is malformed. Our own UI cannot produce this.
    return mediaFailure("invalid_file");
  }

  // A cheap pre-filter, NOT the decision. Refusing an obviously
  // unacceptable type here saves a reservation and a wasted upload; a
  // client that lies gets refused at finalization instead, having
  // gained nothing but a pending row the sweep reclaims.
  if (!isAllowedImageMimeType(input.declaredMimeType)) {
    return mediaFailure("unsupported_format");
  }

  const mediaId = deps.generateMediaId();

  // Throws rather than returns on a malformed id — see
  // InvalidMediaPathError. Both ids are ours by construction at this
  // point, so reaching that is a bug, not a refusal.
  const storagePath = buildMediaObjectPath({
    memorialId: access.memorialId,
    mediaId,
    mimeType: input.declaredMimeType,
  });

  try {
    // The row is written BEFORE the permission is issued, and that
    // order is the anti-orphan strategy in one line: every path we ever
    // hand out is already recorded as `pending`, so an upload that is
    // started and abandoned is always something the sweep can find. The
    // reverse order would create exactly the failure mode we refuse to
    // have — bytes in the bucket that no row knows about.
    //
    // `ownerId` is the VERIFIED one from the access result, never
    // anything the caller sent.
    await deps.mediaRepository.createPending({
      memorialId: access.memorialId,
      ownerId: access.ownerId,
      mediaId,
      storagePath,
      purpose: input.purpose,
      declaredMimeType: input.declaredMimeType,
    });
  } catch {
    // Nothing was reserved and nothing was issued. No cleanup to do.
    return mediaFailure("storage_unavailable");
  }

  try {
    const permission = await deps.objectStore.createUploadPermission({
      path: storagePath,
    });

    return mediaSuccess({
      mediaId,
      storagePath,
      uploadUrl: permission.url,
      uploadToken: permission.token,
    });
  } catch {
    // A pending row now exists for an upload that can never happen. It
    // is deliberately left alone rather than deleted here: the sweep
    // already reclaims exactly this shape, and a compensating delete on
    // an error path is one more thing that can itself fail. Nothing
    // displays a pending media, so the row is inert until then.
    return mediaFailure("storage_unavailable");
  }
}

/**
 * Verify what was actually uploaded, and make the media usable.
 *
 * This is where "never trust the browser" is enforced (mission brief,
 * section 8). Everything the client told us at reservation time was a
 * claim; everything checked here is measured from the stored object.
 *
 * Idempotent: finalizing an already-finalized media returns it
 * unchanged. Retrying after a lost response is a normal thing for a
 * browser on a bad connection to do, and it must not be punished.
 */
export async function finalizeMediaUpload(
  deps: MediaEngineDeps,
  actor: HeritageActor,
  input: { memorialId: string; mediaId: string },
): Promise<MediaResult<Media>> {
  const access = await authorizeMemorialAccess(deps, actor, input.memorialId);
  if (access.status !== "granted") {
    return mediaFailure("access_denied");
  }

  let media: Media | null;
  try {
    media = await deps.mediaRepository.findById({
      memorialId: access.memorialId,
      mediaId: input.mediaId,
    });
  } catch {
    return mediaFailure("storage_unavailable");
  }

  // `null` is "no such media in THIS memorial" — which covers both a
  // media that does not exist and one belonging to another family.
  // Collapsed into `access_denied` so this cannot be used to probe
  // whether a media id is real somewhere else.
  if (media === null) {
    return mediaFailure("access_denied");
  }

  if (media.status === "ready") {
    return mediaSuccess(media);
  }

  // The stored path is a value we read back, so it is checked before
  // it is used. A tampered or corrupted row must never be able to aim
  // a verified-and-authorized operation at another memorial's object.
  if (!isPathWithinMemorial(media.storagePath, access.memorialId)) {
    return mediaFailure("storage_unavailable");
  }

  let stat: { sizeBytes: number } | null;
  try {
    stat = await deps.objectStore.statObject({ path: media.storagePath });
  } catch {
    return mediaFailure("storage_unavailable");
  }

  // The reservation exists but no bytes do: the browser never finished.
  // The pending row stays for the sweep — the user may still be
  // retrying, and the TTL is what decides when that hope expires.
  if (stat === null || stat.sizeBytes <= 0) {
    return mediaFailure("upload_incomplete");
  }

  // Second line of defence behind the bucket's own `file_size_limit`,
  // which is what actually stops an oversized transfer before it is
  // stored. If a file this big is here at all, the bucket limit is
  // misconfigured — refuse it, and say so in the one way a UI can
  // translate.
  if (stat.sizeBytes > MAX_MEDIA_BYTES) {
    await discardUnusableUpload(deps, media);
    return mediaFailure("file_too_large");
  }

  let head: Uint8Array | null;
  try {
    head = await deps.objectStore.readObjectHead({
      path: media.storagePath,
      byteCount: IMAGE_SIGNATURE_BYTES,
    });
  } catch {
    return mediaFailure("storage_unavailable");
  }

  if (head === null) {
    return mediaFailure("upload_incomplete");
  }

  // THE check. Not the extension, not the declared type, not the
  // filename — the bytes. An SVG, a script, an archive or a HEIC
  // photograph all land here as `null`.
  const actualMimeType = detectImageMimeType(head);
  if (actualMimeType === null) {
    await discardUnusableUpload(deps, media);
    return mediaFailure("invalid_file");
  }

  // The path's extension was derived from the type the client
  // DECLARED, so a client that declared JPEG and uploaded a real PNG
  // would leave us with genuine PNG bytes at `original.jpg`. That is
  // refused rather than repaired: an object path whose extension can
  // disagree with its content is a small lie that later code (a CDN, an
  // optimizer, a browser sniffing a download) would be entitled to
  // believe. Renaming instead would mean a copy-then-delete across two
  // Storage calls with no atomicity — a worse trade for a case an
  // honest client never hits.
  if (actualMimeType !== media.mimeType) {
    await discardUnusableUpload(deps, media);
    return mediaFailure("invalid_file");
  }

  let ready: Media | null;
  try {
    // Conditional on the row still being `pending` — see
    // MediaRepository.markReady. Two finalizations racing produce one
    // winner, and a finalization racing the sweep cannot resurrect a
    // reclaimed row.
    ready = await deps.mediaRepository.markReady({
      memorialId: access.memorialId,
      mediaId: input.mediaId,
      mimeType: actualMimeType,
      sizeBytes: stat.sizeBytes,
    });
  } catch {
    return mediaFailure("storage_unavailable");
  }

  if (ready === null) {
    // Lost the race. Re-read: if the other finalization won, this call
    // reports the same success it would have produced itself. If the
    // row is gone (the sweep took it), the upload is simply too late.
    let current: Media | null;
    try {
      current = await deps.mediaRepository.findById({
        memorialId: access.memorialId,
        mediaId: input.mediaId,
      });
    } catch {
      return mediaFailure("storage_unavailable");
    }

    if (current !== null && current.status === "ready") {
      return mediaSuccess(current);
    }

    return mediaFailure("upload_incomplete");
  }

  return mediaSuccess(ready);
}

/**
 * Throw away an upload that arrived but is not acceptable.
 *
 * Storage first, then the row — the same ordering rule as
 * lib/media/delete-media.ts, for the same reason: a row pointing at a
 * missing object is visible and retryable, while an object no row
 * mentions is an orphan nobody can ever find again.
 *
 * Failures are swallowed on purpose. This runs on a path that is
 * ALREADY returning a refusal to the user, and the refusal is the
 * honest answer whether or not the cleanup succeeded. A pending row
 * that survives is reclaimed by the sweep; letting a cleanup error
 * mask `invalid_file` with `storage_unavailable` would tell the user
 * something false.
 */
async function discardUnusableUpload(deps: MediaEngineDeps, media: Media): Promise<void> {
  try {
    // Built through the validated builder rather than by interpolating
    // the ids: this runs on stored values, and the builder is the one
    // place that refuses anything which is not a pair of UUIDs. A
    // hand-rolled template here would be the obvious spot for a
    // traversal to re-enter a codebase that had closed it everywhere
    // else.
    await deps.objectStore.removeByPrefix({
      prefix: buildMediaObjectPrefix({
        memorialId: media.memorialId,
        mediaId: media.id,
      }),
    });
  } catch {
    // Deliberately ignored — see above.
  }

  try {
    await deps.mediaRepository.deleteById({
      memorialId: media.memorialId,
      mediaId: media.id,
    });
  } catch {
    // Deliberately ignored — see above.
  }
}
