-- Mission 011A: transactional foundation for entitlement redemption.
--
-- Two things only, both required for ONE guarantee: a redemption either
-- happens completely or does not exist at all.
--
--   A. Three memorials columns become nullable — the "progressive
--      memorial" correction (see below).
--   B. redeem_entitlement(), the atomic primitive.
--
-- No new table, no new column, no new RLS policy, no policy weakened.
--
-- ---------------------------------------------------------------------
-- A. PROGRESSIVE MEMORIAL — editorial_context / language / slug
-- ---------------------------------------------------------------------
--
-- Redemption creates the technical right to enter a Memorial. It never
-- decides, on the family's behalf, what they want to tell. Three columns
-- were NOT NULL and had no honest value at redemption time:
--
--   editorial_context  the family genuinely chooses "announcement" vs
--                      "remembrance" later; it drives which sections are
--                      valid (config/sections.ts EDITORIAL_CONTEXT_SECTIONS),
--                      so defaulting it would silently pick a product
--                      path for them.
--   language           chosen by the family at the start of the Builder.
--                      config/languages.ts DEFAULT_LANGUAGE stays useful
--                      as an application-level fallback, but it is not a
--                      persisted user decision and must not be written
--                      here as if it were one.
--   slug               the public URL. Its real generation needs the
--                      deceased's name, which does not exist yet at
--                      redemption, and belongs to the publication flow.
--                      No fake name, no temporary public slug, no UUID
--                      dressed up as a URL.
--
-- NULL here is not an accidentally-incomplete memorial: it is explicitly
-- the initial state, before the family has configured anything. No new
-- lifecycle status is introduced for it — `status` stays 'draft', which
-- already means exactly this.
--
-- Audited before writing this: no RLS policy, index, constraint,
-- trigger or SQL function anywhere in supabase/migrations/ reads these
-- three columns. The only structures touching them are their own NOT
-- NULL / CHECK / UNIQUE declarations. The CHECK constraints are
-- deliberately KEPT: in PostgreSQL a CHECK passes when its expression is
-- NULL, so `language in ('en','fr','es')` still rejects 'zz' while
-- allowing NULL — relaxing NOT NULL costs no validation.
--
-- memorials.slug stays UNIQUE. PostgreSQL's default UNIQUE index is
-- NULLS DISTINCT: every NULL is considered distinct from every other, so
-- any number of memorials may sit at slug IS NULL simultaneously, while
-- two identical non-null slugs are still rejected. Verified empirically
-- against this project's target engine (PostgreSQL 16.13:
-- pg_index.indnullsnotdistinct = false on memorials_slug_key) and
-- covered by a dedicated harness check. This is the pre-PG15 behaviour
-- too, and the NULLS NOT DISTINCT option is deliberately NOT used.

alter table memorials
  alter column editorial_context drop not null,
  alter column language          drop not null,
  alter column slug              drop not null;

comment on column memorials.editorial_context is
  'NULL until the family chooses announcement/remembrance in the Builder. Never defaulted at redemption — Mission 011A.';
comment on column memorials.language is
  'NULL until the family chooses a language in the Builder. DEFAULT_LANGUAGE is an application fallback, not a persisted decision — Mission 011A.';
comment on column memorials.slug is
  'NULL until the real slug is generated by the publication flow. UNIQUE is NULLS DISTINCT, so many memorials may be NULL at once — Mission 011A.';

-- ---------------------------------------------------------------------
-- B. redeem_entitlement() — the atomic primitive
-- ---------------------------------------------------------------------
--
-- WHY THIS EXISTS AT ALL. @supabase/supabase-js exposes no transaction
-- API: every .from().insert()/.update() is a separate PostgREST request,
-- hence a separate transaction. A redemption is two writes plus a
-- trigger, and no ordering of two independent transactions avoids a
-- window where one succeeded and the other did not (entitlement consumed
-- with no memorial, or a memorial whose entitlement is still available).
-- A single function call is one statement, therefore one transaction,
-- therefore all-or-nothing.
--
-- WHAT IT DELIBERATELY DOES NOT KNOW. No Etsy, no sales channel, no
-- Offer, no allowedSkins, no culture, no catalogue rule, no UI. It never
-- derives memorial_type or skin_id — it receives them already decided
-- and validated by the TypeScript domain (config/offers.ts,
-- lib/entitlement/offer-skin.ts). HERITAGE product logic stays in
-- TypeScript; this function is an integrity envelope:
--     lock -> verify -> consume -> create -> commit, or nothing.
-- It does enforce the structural constraints the database already owns
-- (the memorial_type / skin_id CHECKs, entitlement_id UNIQUE, the FKs) —
-- that is the database's job, not duplicated product logic.
--
-- SECURITY INVOKER, NOT SECURITY DEFINER — deliberate, minimal
-- privilege. The caller is the server-side service role, which in
-- Supabase carries BYPASSRLS and full DML grants on this schema, so the
-- function needs no ambient privilege of its own to do its work. Keeping
-- it INVOKER means it holds none: it can never become a privilege
-- escalation vector. If EXECUTE were ever granted here by mistake, the
-- body would run with THAT caller's rights, RLS would apply, and the
-- insert into memorials would be refused (no INSERT policy exists for
-- any client role) — the function would simply fail instead of handing
-- out write access. SECURITY DEFINER would do the opposite.
--
-- Contrast with public_memorial_publication_state()
-- (20260829154000_memorials.sql), which genuinely requires SECURITY
-- DEFINER: it is evaluated inside RLS policies as anon/authenticated,
-- roles that must never read `memorials` themselves. Different problem,
-- different answer — the pattern is not applied by reflex here.
--
-- search_path is pinned for determinism. With SECURITY INVOKER it is
-- hygiene rather than a security boundary (a caller manipulating
-- search_path could only ever reach objects it already has rights to),
-- but the function must resolve the same tables on every call.

create or replace function redeem_entitlement(
  p_entitlement_id uuid,
  p_owner_id       uuid,
  p_memorial_type  text,
  p_skin_id        text
)
returns table (memorial_id uuid, outcome text)
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_status   text;
  v_owner_id uuid;
  v_memorial uuid;
begin
  -- THE SERIALIZATION POINT. FOR UPDATE takes a row lock on this one
  -- entitlement for the remainder of the transaction. A concurrent
  -- redemption of the same entitlement blocks here; under READ COMMITTED
  -- (PostgreSQL's default, and Supabase's) it then re-reads the row as
  -- the winner committed it, so it observes status = 'redeemed' and
  -- takes the idempotent or refusal branch below. It can never re-run
  -- the available branch. Two winners are impossible.
  select e.status, e.owner_id
    into v_status, v_owner_id
    from entitlements e
   where e.id = p_entitlement_id
     for update;

  if not found then
    raise exception 'entitlement_not_found' using errcode = 'HH404';
  end if;

  -- Already redeemed: never a second memorial, but not automatically a
  -- fatal error either. A lost response followed by a client retry is a
  -- normal network event, not a corruption — the retry gets the memorial
  -- that already exists.
  if v_status = 'redeemed' then
    if v_owner_id is distinct from p_owner_id then
      -- A different owner claiming a consumed right. Refused outright:
      -- security over convenience.
      raise exception 'entitlement_owned_by_another_owner' using errcode = 'HH403';
    end if;

    select m.id into v_memorial
      from memorials m
     where m.entitlement_id = p_entitlement_id;

    if v_memorial is null then
      -- 'redeemed' with no memorial cannot happen through this function
      -- (both writes commit together). If it is ever observed, it came
      -- from somewhere else and is a real integrity anomaly — surfaced
      -- loudly, never repaired silently by minting a second memorial.
      raise exception 'entitlement_redeemed_without_memorial' using errcode = 'HH500';
    end if;

    return query select v_memorial, 'already_redeemed'::text;
    return;
  end if;

  -- 'revoked' (and any status that is not 'available') consumes nothing
  -- and creates nothing.
  if v_status <> 'available' then
    raise exception 'entitlement_not_available:%', v_status using errcode = 'HH409';
  end if;

  -- Consume, then create. Order is immaterial to the guarantee — both
  -- live or both die with this transaction — but consuming first means
  -- the harness can prove the rollback by making the INSERT fail and
  -- observing that the entitlement is still 'available' afterwards.
  update entitlements
     set status      = 'redeemed',
         owner_id    = p_owner_id,
         redeemed_at = now()
   where id = p_entitlement_id;

  -- editorial_context, language and slug are deliberately absent: they
  -- stay NULL until the family decides. status defaults to 'draft',
  -- enabled_sections to '{}'. The memorials_create_draft trigger
  -- (20260829155000_memorial_content.sql) creates the draft row inside
  -- this same transaction, so it rolls back with everything else.
  insert into memorials (owner_id, entitlement_id, memorial_type, skin_id)
  values (p_owner_id, p_entitlement_id, p_memorial_type, p_skin_id)
  returning id into v_memorial;

  return query select v_memorial, 'redeemed'::text;
end;
$$;

comment on function redeem_entitlement(uuid, uuid, text, text) is
  'Mission 011A. Atomically consumes an available entitlement and creates its one memorial, or returns the existing one when the same owner retries. Integrity envelope only: receives memorial_type/skin_id already decided by the TypeScript domain, knows nothing about offers, skins or sales channels. SECURITY INVOKER — server-side privileged caller only.';

-- Minimal privileges. PostgreSQL grants EXECUTE on new functions to
-- PUBLIC by default; that is revoked first, so no client role inherits
-- it. Only the server-side service role may call this. anon and
-- authenticated are never granted execute, here or anywhere else.
revoke all on function redeem_entitlement(uuid, uuid, text, text) from public;
grant execute on function redeem_entitlement(uuid, uuid, text, text) to service_role;
