-- Mission 019B: the Etsy seller credential store.
--
-- ---------------------------------------------------------------------
-- WHY THIS TABLE EXISTS AT ALL
-- ---------------------------------------------------------------------
--
-- Mission 019B's audit established, and the QG arbitrated, the one fact
-- that forces this migration: Etsy's refresh grant returns a NEW refresh
-- token and revokes the one that was used. An access token lives one
-- hour, Netlify is serverless with no shared memory, so a refresh is
-- unavoidable and frequent — and a refresh token held in an environment
-- variable is stale the moment the first refresh commits, because an
-- env var is not writable at runtime. The channel would then die at the
-- next cold start, silently.
--
-- So the current seller credential needs a durable, writable, strictly
-- server-side home. That is all this table is. It is NOT a business
-- table and it is deliberately not attached to one: no existing HERITAGE
-- table is diverted to hold an integration secret.
--
-- WHAT IT MUST NEVER CONTAIN, and does not: a buyer_user_id, a receipt,
-- an order reference, an email, an IP, a user-agent, or anything about a
-- family. It holds one integration credential and the bookkeeping needed
-- to renew it exactly once at a time. Mission 019B's whole doctrine is
-- that the buyer's Etsy identity is compared in memory and never
-- persisted; this table is not a loophole in that.
--
-- ---------------------------------------------------------------------
-- A. THE SINGLETON
-- ---------------------------------------------------------------------
--
-- There is exactly one Etsy shop, so there is exactly one credential,
-- and the schema says so rather than trusting the application to only
-- ever insert one row. `singleton boolean primary key default true
-- check (singleton)` admits precisely one row: `true`. A second INSERT
-- collides with the primary key, which is what makes the bootstrap in
-- lib/integration/etsy/seller-credential.ts safe under concurrency
-- (`on conflict do nothing`) instead of racing two rows into existence.
--
-- `credential_version` is the concurrency anchor. It is incremented ONLY
-- when the credential itself changes — never when a lease is taken or
-- released. That distinction is load-bearing: it is what lets a refresh
-- that took a while still commit its result, while still making it
-- impossible for an older credential to overwrite a newer one. See
-- section C.

create table etsy_seller_credentials (
  singleton boolean primary key default true,

  -- The current Etsy refresh token. This is THE source of truth once the
  -- row exists: ETSY_SELLER_REFRESH_TOKEN is a bootstrap seed only, and
  -- can never overwrite this column (see the bootstrap's
  -- `on conflict do nothing`).
  refresh_token text not null,

  -- Cache only. NULL is always legitimate and simply means "refresh
  -- before the next call". Cached so that a hot instance does not spend
  -- a refresh — and therefore rotate the refresh token — on every single
  -- request, which is the behaviour that makes rotation dangerous in the
  -- first place.
  access_token text,
  access_token_expires_at timestamptz,

  -- Incremented on every credential change, and on no other event.
  credential_version bigint not null default 1,

  -- The refresh lease (section C). Both NULL means nobody is refreshing.
  -- `lease_holder` is a random per-attempt id generated by the
  -- application, not a user id and not an auth id — it identifies an
  -- attempt, never a person.
  lease_holder uuid,
  lease_expires_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint etsy_seller_credentials_singleton_check check (singleton),

  -- A non-empty credential or no row at all. An empty string would be a
  -- credential-shaped value that fails every Etsy call for a reason no
  -- log would explain.
  constraint etsy_seller_credentials_refresh_token_not_blank
    check (length(btrim(refresh_token)) > 0),
  constraint etsy_seller_credentials_access_token_not_blank
    check (access_token is null or length(btrim(access_token)) > 0),

  -- A cached access token without its expiry is unusable (we could never
  -- know when to stop trusting it) and an expiry without a token is
  -- meaningless. They are set together or not at all.
  constraint etsy_seller_credentials_access_token_pairing check (
    (access_token is null and access_token_expires_at is null)
    or (access_token is not null and access_token_expires_at is not null)
  ),

  -- Same reasoning for the lease: a holder without a deadline could
  -- never expire, which is exactly the state that would wedge the
  -- channel forever after one crash.
  constraint etsy_seller_credentials_lease_pairing check (
    (lease_holder is null and lease_expires_at is null)
    or (lease_holder is not null and lease_expires_at is not null)
  )
);

comment on table etsy_seller_credentials is
  'Mission 019B. Singleton store for HERITAGE''s own Etsy SELLER credential (refresh token, plus the access token as a cache). Exists because Etsy rotates and revokes the refresh token on every refresh, which an environment variable cannot survive. service_role only: no policy, no grant to anon or authenticated, never read from a Client Component. Contains no buyer identity, no receipt, no order reference and no personal data of any kind.';
comment on column etsy_seller_credentials.refresh_token is
  'Current Etsy refresh token — the source of truth once this row exists. ETSY_SELLER_REFRESH_TOKEN is a bootstrap seed only and can never overwrite this value.';
comment on column etsy_seller_credentials.credential_version is
  'Incremented ONLY when the credential changes, never on lease acquisition or release. The guard that makes it impossible for an older credential to overwrite a newer one.';
comment on column etsy_seller_credentials.lease_holder is
  'Random per-attempt identifier of the process currently allowed to call Etsy''s refresh grant. Not a user id, not an auth id — it identifies an attempt, never a person.';

-- No index beyond the primary key. The table holds one row; every access
-- is `where singleton` and is served by the primary key itself.

create trigger etsy_seller_credentials_set_updated_at
  before update on etsy_seller_credentials
  for each row
  execute function set_updated_at();

-- ---------------------------------------------------------------------
-- B. PRIVILEGES — WHY anon AND authenticated CAN DO NOTHING
-- ---------------------------------------------------------------------
--
-- Mission 013C's doctrine, applied without exception: revoke everything
-- from every application role by name — PUBLIC included, so this never
-- depends on PUBLIC holding nothing today — then grant only what a wired
-- server path provably needs.
--
-- `anon` and `authenticated` receive NOTHING. Not SELECT, not INSERT,
-- not UPDATE, not DELETE, not TRUNCATE, not REFERENCES, not TRIGGER, not
-- MAINTAIN. That is the whole protection, and it is stronger than a
-- column-level revoke or an RLS policy could be: a role holding no
-- privilege on the table cannot reach any column, including any column a
-- future migration adds. PostgREST exposes nothing it has no privilege
-- for, so this table is not reachable through the REST API by a browser
-- session at all — which is the only way a browser could ever have
-- touched it.
--
-- RLS is enabled with NO policy, for any role. For anon/authenticated
-- that is a deliberate second lock on a door the grants already keep
-- shut. service_role carries BYPASSRLS and never evaluates a policy
-- here — its access is the explicit grant below, recorded in Git, not an
-- inheritance from the platform's defaults.
--
-- service_role gets SELECT, INSERT and UPDATE:
--   SELECT  read the current credential and the lease state
--   INSERT  the one-time bootstrap (`on conflict do nothing`)
--   UPDATE  take/release the lease, and store a renewed credential
--
-- DELETE is granted to nobody. Losing this row means re-bootstrapping
-- the channel by hand, so no code path may be able to remove it — not
-- even by accident, not even in a future bug.

alter table etsy_seller_credentials enable row level security;

revoke all privileges on table etsy_seller_credentials
  from public, anon, authenticated, service_role;
grant select, insert, update on table etsy_seller_credentials to service_role;

-- ---------------------------------------------------------------------
-- C. THE CONCURRENCY CONTRACT THIS SCHEMA GUARANTEES
-- ---------------------------------------------------------------------
--
-- The algorithm lives in lib/integration/etsy/seller-credential.ts and is
-- tested there. What this schema contributes — and what makes the
-- algorithm correct rather than merely careful — is:
--
--   1. LEASE ACQUISITION IS ONE STATEMENT. The application takes the
--      lease with a single conditional UPDATE:
--
--        update etsy_seller_credentials
--           set lease_holder = <attempt>, lease_expires_at = <now+30s>
--         where singleton
--           and (lease_expires_at is null or lease_expires_at < <now>)
--        returning ...
--
--      One statement, so PostgreSQL row locking decides the winner.
--      Concurrent callers cannot both match: the second waits for the
--      first to commit, then re-evaluates the WHERE clause against the
--      committed row and matches nothing. There is no read-then-write
--      window anywhere in this path.
--
--   2. LOSERS NEVER CALL ETSY. A caller that fails to take the lease
--      does not touch the refresh grant at all — it waits and re-reads,
--      because the winner is about to publish a fresh access token. Two
--      processes calling the refresh grant with the same refresh token
--      is precisely how one of the two resulting tokens gets revoked and
--      lost, and this is what prevents it.
--
--   3. A CRASHED HOLDER RECOVERS BY ITSELF. The lease carries a short
--      deadline, so a process that dies mid-refresh blocks nobody past
--      it. No cleanup job, no manual intervention.
--
--   4. AN OLDER CREDENTIAL CAN NEVER OVERWRITE A NEWER ONE. The write
--      that stores a renewed credential is guarded on
--      `credential_version = <the version read at acquisition>`, and the
--      same statement increments it. A slow winner whose lease expired
--      while another attempt already published a newer credential will
--      find the version moved and write nothing at all. This — not the
--      lease — is the actual safety property; the lease only makes the
--      collision rare, the version guard makes losing it harmless.
--
--   5. NO TRANSACTION IS HELD OPEN ACROSS THE HTTP CALL. Acquisition,
--      the Etsy request, and the store are three separate statements by
--      construction: the lease exists exactly so that exclusivity does
--      not require a long-lived database transaction wrapped around a
--      network call to a third party.
--
-- What this schema deliberately does NOT do is add an RPC. Every step
-- above is a single conditional UPDATE or INSERT expressible directly,
-- so a PL/pgSQL wrapper would add a privileged object to audit and to
-- keep in sync with the application, for no atomicity it does not
-- already have.
